
name: FPGA CI


on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  Copy:
    runs-on: self-hosted
    steps:
      
      - uses: actions/checkout@v2

      
      - name: Notices
        run: |
          echo ----------ACTIONS ARE ACTIVATED------------
          echo Copying files on FPGA

      - name: Copy
        run: |
          make clone
  #Run:
  #  runs-on: ubuntu-latest
  #  needs: Copy
  #  steps:
  #    - name: Notices
  #      run: |
  #        echo Running files on FPGA
#
#      - name: Run
#        run: |
#          make run